ShopOnline/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopOnline.Data;
using ShopOnline.Models;
using ShopOnline.Repository;


namespace ShopOnline.Controllers
{
    public class CategoryController : Controller
    {
        //private readonly ApplicationDbContext _context;
        private Repository.CategoryRepository _context;
        private Repository.ProductRepository _productRepository;
        public CategoryController(ApplicationDbContext context, ProductRepository productRepository)
        {
            _context = new Repository.CategoryRepository(context);
            _productRepository = productRepository;
        }

        // GET: Category
        public ActionResult Index()
        {
              var category=_context.GetAllCategories();
                return View("Index",category);
        }
       
        // GET: Category/Details/5
        public ActionResult Details(Guid id)
        {
           

            var category = _context.GetCategoryById(id);
            return View("DetailsCategory", category);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View("CreateCategory");
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {

              try {
                  Models.CategoryModel model = new Models.CategoryModel();
                  var task = TryUpdateModelAsync(model);
                  task.Wait();
                  if (task.Result)
                  {
                      _context.InsertCategory(model);
                  }
                  return RedirectToAction(nameof(Index));
            }
              catch
              {
                  return View("CreateCategory");
              }
              return RedirectToAction(nameof(Index));
           

        }

        // GET: Category/Edit/5
        public ActionResult Edit(Guid id)
        {
           

            var category =  _context.GetCategoryById(id);
            if (category == null)
            {
                return NotFound();
            }
            return View("EditCategory",category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guid id, IFormCollection collection)
        {
            try
            {
                var model = new Models.CategoryModel();
                var task = TryUpdateModelAsync(model);
                task.Wait();
                if (task.Result)
                {
                    _context.UpdateCategory(model);
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index", id);
                }

            }
            catch
            {
                return RedirectToAction("Index", id);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Category/Delete/5
        public ActionResult Delete(Guid id)
        {
            

            var category = _context.GetCategoryById(id);
            if (category == null)
            {
                return NotFound();
            }

            return View("DeleteCategory", category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id,IFormCollection collection)
        {
            try
            {
                _context.DeleteCategory(id);
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View("DeleteCategory");
            }
        }

        
    }
}

ShopOnline/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopOnline.Data;
using System.IO;
//using ShopOnline.Models.DBObjects;
using Microsoft.Web.Helpers;
using Newtonsoft.Json;
using javax.tools;
using java.awt.image;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using ShopOnline.Models;
using com.sun.org.apache.bcel.@internal.generic;
using ShopOnline.Models.DBObjects;
using System.Text;
using com.sun.security.ntlm;
using com.sun.corba.se.impl.orbutil.concurrent;
using Microsoft.AspNetCore.Authorization;

namespace ShopOnline.Controllers
{
    [Authorize(Roles = "Admin")]

    public class ProductController : Controller
    {
       // private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;
        private Repository.ProductRepository _context;
        private Repository.CategoryRepository _cat;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private ApplicationDbContext context;


        public ProductController(ApplicationDbContext context1,IHostingEnvironment hostingEnvironment, IWebHostEnvironment webHostEnvironment, ILogger<ProductController> logger)
        {
            _context = new Repository.ProductRepository(context1);
            _cat = new Repository.CategoryRepository(context1);
            _hostingEnvironment = hostingEnvironment;
            _webHostEnvironment = webHostEnvironment;
            context = context1;
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));

        }

        // GET: Product
        public ActionResult Index()
        {
            var products = _context.GetAllProducts();

            foreach (var product in products)
            {
                product.IdCategoryNavigation = _context.GetCategoryById(product.IdCategory);
                ViewBag.CategoryNameForProduct = product.IdCategoryNavigation.Name;
                
            }


            return View(products);
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null || context.Products == null)
            {
                return NotFound();
            }


            var product = _context.GetProductById(id);
            
            return View("Details",product);
        }
        
        // GET: Product/Create
        public ActionResult Create()
        {
             ViewData["IdCategory"] = new SelectList(_cat.GetAllCategories(), "IdCategory","Name");

            ViewData["Image"] = new SelectList(_cat.GetAllCategories(), "IdCategory", "Name");
            return View("Create");
            
        }

        ILogger<ProductController> _logger;
        // POST: Product/Create Cu repository
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
         public async Task<IActionResult> Create([Bind("IdProduct,Name,Description,IdCategory,Price,StockQuantity,Image")] ProductModel model, IFormFile image)
         {

                 try
                 {
                    // Models.ProductModel model = new Models.ProductModel();
                 if (image != null && image.Length > 0)
                 {
                     var imagePath = Path.Combine(_hostingEnvironment.WebRootPath, "Products", image.FileName);

                     using (var stream = new FileStream(imagePath, FileMode.Create))
                     {
                         await image.CopyToAsync(stream);
                     }

                     model.Image = "/Products/" + image.FileName; 
                 }

                     _context.InsertProduct(model);
                    return RedirectToAction(nameof(Index));

             }
                 catch 
                 {
                     ModelState.AddModelError(string.Empty, "Error saving the product. Please try again.");
                     return View("Create"); 

                  }

             return RedirectToAction(nameof(Index));
         }
        
        
        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var product = _context.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["IdCategory"] = new SelectList(context.Categories, "IdCategory", "Name", product.IdCategory);
            return View("Edit",product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("IdProduct,Name,Description,IdCategory,Price,StockQuantity,Image")] ProductModel product, IFormFile image)
        {
            if (id != product.IdProduct)
            {
                return NotFound();
            }
            
            ViewData["IdCategory"] = new SelectList(context.Categories, "IdCategory", "IdCategory", product.IdCategory);
            return View(product);
        }
        
        
        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            var product = _context.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            return View("Delete", product);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                var product = _context.GetProductById(id);
                _context.DeleteProduct(id,product.Image);
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View("Delete");
            }
        }

        
        
    }
}

ShopOnline/Controllers/TVAController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopOnline.Data;
using ShopOnline.Models;

namespace ShopOnline.Controllers
{
    public class TvaController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Repository.TvaRepository _repository;
        private readonly Repository.CategoryRepository _cat;
        public TvaController(ApplicationDbContext context)
        {
            _context = context;
            _repository = new Repository.TvaRepository(context);
            _cat = new Repository.CategoryRepository(context);
        }
        // GET: TvaController
        public ActionResult Index()
        {
            var tvas = _repository.GetAllTVAs();
            foreach (var tva in tvas)
            {
                tva.IdCategoryNavigation = _repository.GetCategoryById(tva.IdCategory);
                ViewBag.CategoryNameForProduct = tva.IdCategoryNavigation.Name;
            }
            return View(tvas);
        }

        // GET: TvaController/Details/5
        public ActionResult Details(Guid id)
        {
            var tva = _repository.GetTvaById(id);
            tva.IdCategoryNavigation = _repository.GetCategoryById(tva.IdCategory);
            ViewBag.CategoryNameForProduct = tva.IdCategoryNavigation.Name;
            return View("Details", tva);
        }

        // GET: TvaController/Create
        public ActionResult Create()
        {
            ViewData["IdCategory"] = new SelectList(_cat.GetAllCategories(), "IdCategory", "Name");
            return View("Create");
        }

        // POST: TvaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTva,Tval,IdCategory")] TvaModel model)
        {
            try
            {
                _repository.InsertTva(model);
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View("Create");
            }

            return RedirectToAction(nameof(Index));

        }


        // GET: TvaController/Edit/5
        public ActionResult Edit(Guid id)
        {
            var tva = _repository.GetTvaById(id);
            if (tva == null)
            {
                return NotFound();
            }

            ViewData["IdCategory"] = new SelectList(_context.Categories, "IdCategory", "Name", tva.IdCategory);
            return View("Edit", tva);
        }

        // POST: TvaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid id, [Bind("IdTva, Tval, IdCategory")] Models.TvaModel model)
        {
            try
            {

                model.IdTva = id;

                _repository.UpdateTva(model);
                return RedirectToAction("Index");


            }
            catch
            {
                return RedirectToAction("Index", id);
            }
            return RedirectToAction(nameof(Index));
        }


        // GET: TvaController/Delete/5
        public ActionResult Delete(Guid id)
        {
            var tva = _repository.GetTvaById(id);
            if (tva == null)
            {
                return NotFound();
            }
            tva.IdCategoryNavigation = _repository.GetCategoryById(tva.IdCategory);
            ViewBag.CategoryNameForProduct = tva.IdCategoryNavigation.Name;
            return View("Delete", tva);
        }

        // POST: TvaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid id, IFormCollection collection)
        {
            try
            {
                _repository.DeleteTva(id);
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View("Delete");
            }
        }

    }
}

ShopOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopOnline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopOnline.styles.css" asp-append-version="true" />
</head>
<body>
   

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
            
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                      
                        <li>

                            <form class="form-inline my-2 my-lg-0" method="get" asp-controller="Home" asp-action="Search">
                                <input class="form-control mr-sm-2" type="search" placeholder="Caută..." name="q" aria-label="Caută">

                            </form>


                        </li>
                    </ul>
                    <ul class="navbar-nav" style="margin-right:2%">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" align="center">
            &copy; 2023 - ShopOnline - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShopOnline/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopOnline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopOnline.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AdminIndex">Home</a>
                        </li>
                         <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Produse</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categorii</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Tva" asp-action="Index">TVA</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="UsersOrders">Orders</a>
                        </li>
                        <li>

                            <form class="form-inline my-2 my-lg-0" method="get" asp-controller="Home" asp-action="Search">
                                <input class="form-control mr-sm-2" type="search" placeholder="Caută..." name="q" aria-label="Caută">

                            </form>


                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" align="center">
            &copy; 2023 - ShopOnline - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>